import { ArtisanProfile, BuyerProfile, MarketOpportunity, Product, Enquiry, User } from '../types';

export const mockUsers: User[] = [
  {
    id: 'user-artisan-1',
    name: 'Master Artisan',
    email: 'artisan@kalasetu.in',
    role: 'artisan',
    phone: '+91 94432 18721',
    location: 'Madurai & Thanjavur Cluster, Tamil Nadu',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
    languagePreference: 'ta',
  },
  {
    id: 'user-buyer-1',
    name: 'Procurement Partner',
    email: 'procurement@kalasetu.in',
    role: 'buyer',
    phone: '+91 98210 45678',
    location: 'Mumbai & Bangalore',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    languagePreference: 'en',
  },
];

export const mockArtisans: ArtisanProfile[] = [
  {
    id: 'artisan-1',
    userId: 'user-artisan-1',
    name: 'Master Artisan',
    craftTradition: 'Traditional Terracotta Sculpture & Kathakali Folk Jewelry',
    craftTradition_ta: 'பாரம்பரிய சுடுமண் சிற்பக்கலை மற்றும் கதகளி நாட்டுப்புற நகைகள்',
    craftTradition_hi: 'पारंपरिक टेराकोटा मूर्तिकला एवं कथकली लोक आभूषण',
    clusterLocation: 'Madurai & Chettinad, Tamil Nadu',
    clusterLocation_ta: 'மதுரை மற்றும் செட்டிநாடு, தமிழ்நாடு',
    clusterLocation_hi: 'मदुरै और चेट्टीनाड, तमिलनाडु',
    experienceYears: 28,
    bio_en:
      'A 3rd generation master clay sculptor trained in ancestral open-fire terracotta sculpting. Recognized by the All India Handicrafts Board for preserving classical temple motif jewellery and regional folk figurines.',
    bio_ta:
      'மூன்றாம் தலைமுறை சுடுமண் சிற்ப மாஸ்டர். திறந்தவெளி சூளை சுடுமண் கலையில் தேர்ச்சி பெற்றவர். பாரம்பரிய கோவில் கலை வடிவ நகைகள் மற்றும் நாட்டுப்புற உருவங்களை பாதுகாத்ததற்காக அகில இந்திய கைவினை வாரியத்தால் அங்கீகரிக்கப்பட்டவர்.',
    bio_hi:
      'तीसरी पीढ़ी की मास्टर टेराकोटा मूर्तिकार, जिन्होंने पूर्वजों की खुली भट्टी मिट्टी शिल्प में महारत हासिल की है। पारंपरिक मंदिर आभूषणों और लोक आकृतियों के संरक्षण के लिए अखिल भारतीय हस्तशिल्प बोर्ड द्वारा सम्मानित।',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=1200&auto=format&fit=crop&q=80',
    giTagCertified: true,
    giCertificateNumber: 'GI-IN-TN-2018-094',
    stateAwardee: true,
    nationalMeritHolder: true,
    community: 'Tamil Nadu Kulalar Terracotta Artisans Guild',
    totalProductsListed: 8,
    completedOrders: 142,
    rating: 4.9,
    contactNumber: '+91 94432 18721',
    languagesSpoken: ['Tamil', 'English', 'Malayalam'],
  },
  {
    id: 'artisan-2',
    userId: 'user-artisan-2',
    name: 'Craft Guild Lead',
    craftTradition: 'Tribal Bamboo Weaving & Sustainable Cane Craft',
    craftTradition_ta: 'பழங்குடியினர் மூங்கில் நெசவு மற்றும் பிரம்பு கைவினை',
    craftTradition_hi: 'आदिवासी बांस बुनाई एवं प्राकृतिक बेंत शिल्प',
    clusterLocation: 'Baripada, Mayurbhanj, Odisha',
    clusterLocation_ta: 'பரிபதா, மயூர்பஞ்ச், ஒடிசா',
    clusterLocation_hi: 'बारीपदा, मयूरभंज, ओडिशा',
    experienceYears: 22,
    bio_en:
      'Santhal tribal artisan guild leader specializing in high-tensile fine bamboo strips woven into storage hampers, organic tea baskets, and architectural lamp shades using non-toxic herbal smoking preservation.',
    bio_ta:
      'சந்தால் பழங்குடி கைவினைஞர் குழுத் தலைவர். மூங்கில் நார்களைக் கொண்டு உணவு கூடைகள், இயற்கை தேயிலை கூடைகள் மற்றும் விளக்கு நிழல்களை உருவாக்கும் கைவினை கலைஞர்.',
    bio_hi:
      'संथाल आदिवासी शिल्पकार संघ के प्रमुख, जो गैर-विषाक्त प्राकृतिक धूम्र संरक्षण का उपयोग करके उच्च गुणवत्ता वाली बांस की टोकरियां और लैंप शेड बनाते हैं।',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?w=1200&auto=format&fit=crop&q=80',
    giTagCertified: true,
    giCertificateNumber: 'GI-IN-OD-2020-112',
    stateAwardee: true,
    nationalMeritHolder: false,
    community: 'Mayurbhanj Forest Craft Collective',
    totalProductsListed: 6,
    completedOrders: 98,
    rating: 4.8,
    contactNumber: '+91 94371 67890',
    languagesSpoken: ['Odia', 'Hindi', 'English'],
  },
  {
    id: 'artisan-3',
    userId: 'user-artisan-3',
    name: 'Master Craftsman',
    craftTradition: 'GI-Tagged Jaipur Blue Pottery & Persian Floral Ceramics',
    craftTradition_ta: 'புவிசார் குறியீடு பெற்ற ஜெய்ப்பூர் நீல மண்பாண்டம் & மலர் பீங்கான் கலை',
    craftTradition_hi: 'जीआई-टैग प्राप्त जयपुर ब्लू पॉटरी एवं पुष्प सिरेमिक शिल्प',
    clusterLocation: 'Kot Jewar & Jaipur, Rajasthan',
    clusterLocation_ta: 'ஜெய்ப்பூர், ராஜஸ்தான்',
    clusterLocation_hi: 'कोट जेवर एवं जयपुर, राजस्थान',
    experienceYears: 34,
    bio_en:
      'Senior master craftsman of clay-less blue pottery using Egyptian paste, quartz powder, and natural cobalt oxides. Preserving centuries-old royal Mughal and Rajput patterns with glassy non-fading glaze.',
    bio_ta:
      'குவார்ட்ஸ் தூள் மற்றும் கோபால்ட் சாயங்களைப் பயன்படுத்தி களிமண் இல்லாத பாரம்பரிய நீல மண்பாண்டங்களை உருவாக்கும் மூத்த கைவினை நிபுணர்.',
    bio_hi:
      'क्वार्ट्ज पाउडर और प्राकृतिक कोबाल्ट ऑक्साइड का उपयोग करके पारंपरिक ब्लू पॉटरी बनाने वाले वरिष्ठ शिल्पकार।',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=1200&auto=format&fit=crop&q=80',
    giTagCertified: true,
    giCertificateNumber: 'GI-IN-RJ-2008-045',
    stateAwardee: true,
    nationalMeritHolder: true,
    community: 'Rajasthan Shilp Kala Parishad',
    totalProductsListed: 12,
    completedOrders: 215,
    rating: 5.0,
    contactNumber: '+91 98290 33412',
    languagesSpoken: ['Hindi', 'Rajasthani', 'English'],
  },
];

export const mockBuyers: BuyerProfile[] = [
  {
    id: 'buyer-1',
    userId: 'user-buyer-1',
    organizationName: 'Sustainable Retail Store',
    buyerType: 'Retail Boutique',
    location: 'Mumbai & Bangalore',
    website: 'https://sustainableretail.example.com',
    verifiedGST: true,
    procurementBudget: '₹15,00,000 / quarter',
  },
  {
    id: 'buyer-2',
    userId: 'user-buyer-2',
    organizationName: 'Heritage Hospitality Group',
    buyerType: 'Corporate Gifting',
    location: 'Udaipur & New Delhi',
    website: 'https://heritagehospitality.example.com',
    verifiedGST: true,
    procurementBudget: '₹40,00,000 / year',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-1',
    artisanId: 'artisan-1',
    artisanName: 'Master Artisan',
    artisanLocation: 'Madurai, Tamil Nadu',
    imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80',
    title_en: 'Handcrafted Kathakali Face Terracotta Necklace Set',
    title_ta: 'கைவினை கதகளி முக சுடுமண் நெக்லஸ் தொகுப்பு',
    title_hi: 'हस्तनिर्मित कथकली मुख टेराकोटा हार सेट',
    category_en: 'Handmade Jewellery',
    category_ta: 'கைவினை நகைகள்',
    category_hi: 'हस्तनिर्मित आभूषण',
    subcategory_en: 'Terracotta Neckpieces & Earrings',
    subcategory_ta: 'சுடுமண் கழுத்தணிகள் மற்றும் காதணிகள்',
    subcategory_hi: 'टेराकोटा कंठहार और झुमके',
    material_en: 'Terracotta Clay, Cotton Thread, Natural Mineral Pigments',
    material_ta: 'சுடுமண் களிமண், பருத்தி நூல், இயற்கை கனிம சாயங்கள்',
    material_hi: 'टेराकोटा मिट्टी, सूती धागा, प्राकृतिक खनिज रंग',
    technique_en: 'Hand-moulded and hand-painted miniature firing',
    technique_ta: 'கைகளால் வார்க்கப்பட்டு, இயற்கை முறையில் சுடப்பட்டு வரையப்பட்டது',
    technique_hi: 'हाथ से गढ़ा हुआ एवं भट्टी में पकाया बारीक चित्रकारी कार्य',
    style_en: 'Traditional Folk & Temple Art',
    style_ta: 'பாரம்பரிய நாட்டுப்புற மற்றும் கோவில் கலை',
    style_hi: 'पारंपरिक लोक एवं मंदिर कला',
    colors: ['Terracotta Red', 'Vivid Green', 'Warm Mustard', 'Ebony Black'],
    potential_uses_en: [
      'Ethnic Wear Accessory',
      'Cultural Event Jewellery',
      'Artisan Gift Item',
      'Statement Fashion Accessory',
    ],
    potential_uses_ta: [
      'பாரம்பரிய ஆடை அணிகலன்',
      'கலாச்சார நிகழ்வு நகைகள்',
      'கைவினை பரிசுப் பொருள்',
      'தனித்துவமிக்க நாகரிக அணிகலன்',
    ],
    potential_uses_hi: [
      'पारंपरिक पोशाक आभूषण',
      'सांस्कृतिक समारोह आभूषण',
      'हस्तशिल्प उपहार वस्तु',
      'आधुनिक एथनिक फैशन सहायक',
    ],
    keywords: ['terracotta', 'kathakali', 'handcrafted', 'folk art', 'clay jewelry', 'necklace', 'eco-friendly'],
    description_en:
      'An exquisite handcrafted terracotta necklace set featuring the expressive face of Kathakali, inspired by classical performing arts. Sculpted from fine riverbed clay, kiln-fired and hand-painted with long-lasting vibrant eco-friendly pigments.',
    description_ta:
      'செவ்வியல் கலைகளால் ஈர்க்கப்பட்ட கதகளியின் முகபாவனைகளை கொண்ட நுட்பமான கைவினை சுடுமண் நெக்லஸ் தொகுப்பு. ஆற்று களிமண்ணில் வடிவமைக்கப்பட்டு இயற்கை சாயங்களால் அழகாக வரையப்பட்டது.',
    description_hi:
      'शास्त्रीय प्रदर्शन कला से प्रेरित, कथकली के भावपूर्ण चेहरे वाला उत्कृष्ट हस्तनिर्मित टेराकोटा हार सेट। उच्च गुणवत्ता वाली नदी की मिट्टी से निर्मित और प्राकृतिक रंगों से सजाया गया।',
    tags_en: ['Terracotta', 'Handcrafted', 'Kathakali', 'Folk Art', 'Sustainable Jewellery', 'GI Craft'],
    tags_ta: ['சுடுமண்', 'கைவினை', 'கதகளி', 'நாட்டுப்புற கலை', 'சுற்றுச்சூழல் நட்பு', 'மண் நகை'],
    tags_hi: ['टेराकोटा', 'हस्तनिर्मित', 'कथकली', 'लोक कला', 'पर्यावरण-अनुकूल', 'मिट्टी आभूषण'],
    pricePerUnit: 1450,
    currency: 'INR',
    minimumOrderQuantity: 15,
    leadTimeDays: 14,
    stockAvailable: 45,
    isPublished: true,
    createdAt: '2026-08-20T10:30:00Z',
    confidenceScore: 96,
  },
  {
    id: 'prod-2',
    artisanId: 'artisan-2',
    artisanName: 'Craft Guild Lead',
    artisanLocation: 'Mayurbhanj, Odisha',
    imageUrl: 'https://images.unsplash.com/photo-1590483736622-39da86788790?w=800&auto=format&fit=crop&q=80',
    title_en: 'Handmade Natural Bamboo Nested Storage Baskets (Set of 3)',
    title_ta: 'இயற்கை மூங்கில் சேமிப்பு கூடைகள் (3 கூடைகள் தொகுப்பு)',
    title_hi: 'हस्तनिर्मित प्राकृतिक बांस भंडारण टोकरी सेट (3 का सेट)',
    category_en: 'Home Decor & Storage',
    category_ta: 'வீட்டு அலங்காரம் & சேமிப்பு',
    category_hi: 'गृह सज्जा एवं भंडारण',
    subcategory_en: 'Woven Baskets & Organizers',
    subcategory_ta: 'நெய்யப்பட்ட கூடைகள் & அமைப்பாளர்கள்',
    subcategory_hi: 'बुनी हुई टोकरियां एवं आयोजक',
    material_en: 'Wild Hill Bamboo, River Cane Splints, Organic Linseed Polish',
    material_ta: 'காட்டு மூங்கில், நதி பிரம்பு, இயற்கை ஆளி விதை பாலிஷ்',
    material_hi: 'प्राकृतिक पहाड़ी बांस, नदी की बेंत, जैविक अलसी पॉलिश',
    technique_en: 'Fine twill weave with double-rim reinforcement and herb-smoked seasoning',
    technique_ta: 'இரட்டை விளிம்பு வலுவூட்டல் மற்றும் மூலிகை புகை பதப்படுத்தலுடன் நேர்த்தியான நெசவு',
    technique_hi: 'मजबूत दोहरी रिम और हर्बल धूमन द्वारा तैयार बारीक बुनाई',
    style_en: 'Tribal Minimalist & Eco-Living',
    style_ta: 'பழங்குடியினர் எளிய சூழல் நட்பு நடை',
    style_hi: 'आदिवासी सादगीपूर्ण एवं पर्यावरण-अनुकूल शैली',
    colors: ['Golden Bamboo', 'Honey Amber', 'Natural Tan'],
    potential_uses_en: [
      'Sustainable Retail Store Merchandising',
      'Pantry & Wardrobe Organic Organizer',
      'Eco-friendly Corporate Gift Hamper',
      'Hospitality Spa Towel Basket',
    ],
    potential_uses_ta: [
      'நிலையான சில்லறை விற்பனை பொருள்',
      'இயற்கை சேமிப்பு கூடை',
      'சுற்றுச்சூழல் நட்பு கார்ப்பரேட் பரிசு பேக்',
      'ஸ்பா மற்றும் உணவக பயன்பாடு',
    ],
    potential_uses_hi: [
      'सस्टेनेबल रिटेल स्टोर उत्पाद',
      'घरेलू जैविक भंडारण एवं आयोजक',
      'पर्यावरण-अनुकूल कॉर्पोरेट उपहार हैंपर',
      'होटल एवं स्पा तौलिया टोकरी',
    ],
    keywords: ['bamboo', 'baskets', 'cane', 'handmade', 'sustainable', 'storage', 'eco-friendly', 'organic'],
    description_en:
      'Set of three nesting baskets hand-woven from matured wild bamboo harvested responsibly from Odisha forests. Flexible yet extremely sturdy, naturally treated against pests using traditional herbal smoking.',
    description_ta:
      'ஒடிசா காடுகளிலிருந்து பெறப்பட்ட முதிர்ந்த மூங்கிலிலிருந்து கையால் நெய்யப்பட்ட மூன்று கூடைகளின் தொகுப்பு. மிகவும் உறுதியானது மற்றும் பூச்சிகளுக்கு எதிராக மூலிகைகளால் இயற்கையாக பதப்படுத்தப்பட்டது.',
    description_hi:
      'ओडिशा के जंगलों से जिम्मेदारी से चुने गए बांस से हाथ से बुनी गई तीन टोकरियों का सेट। मजबूत, लचीला और पारंपरिक हर्बल धुएं से कीट-रोधी बनाया गया।',
    tags_en: ['Bamboo Basket', 'Sustainable Living', 'Eco Friendly', 'Tribal Craft', 'Storage Organizer'],
    tags_ta: ['மூங்கில் கூடை', 'சூழல் நட்பு', 'பழங்குடி கைவினை', 'சேமிப்பு கூடை'],
    tags_hi: ['बांस की टोकरी', 'पर्यावरण-अनुकूल', 'आदिवासी शिल्प', 'भंडारण टोकरी'],
    pricePerUnit: 1850,
    currency: 'INR',
    minimumOrderQuantity: 20,
    leadTimeDays: 18,
    stockAvailable: 80,
    isPublished: true,
    createdAt: '2026-08-25T14:15:00Z',
    confidenceScore: 97,
  },
  {
    id: 'prod-3',
    artisanId: 'artisan-3',
    artisanName: 'Master Craftsman',
    artisanLocation: 'Jaipur, Rajasthan',
    imageUrl: 'https://images.unsplash.com/photo-1615529182904-14819c35db37?w=800&auto=format&fit=crop&q=80',
    title_en: 'Jaipur Blue Pottery Hand-Glazed Floral Decorative Vase (12-inch)',
    title_ta: 'ஜெய்ப்பூர் நீல மண்பாண்ட மலர் அலங்கார குவளை (12 அங்குலம்)',
    title_hi: 'जयपुर ब्लू पॉटरी हस्त-चित्रित पुष्प सजावटी फूलदान (12 इंच)',
    category_en: 'Home Decor & Pottery',
    category_ta: 'வீட்டு அலங்காரம் & மண்பாண்டங்கள்',
    category_hi: 'गृह सज्जा एवं मिट्टी के बर्तन',
    subcategory_en: 'Decorative Ceramic Vases',
    subcategory_ta: 'அலங்கார பீங்கான் குவளைகள்',
    subcategory_hi: 'सजावटी सिरेमिक फूलदान',
    material_en: 'Quartz Powder, Fuller Earth (Multani Mitti), Natural Cobalt Glaze',
    material_ta: 'குவார்ட்ஸ் தூள், முல்தானி மிட்டி, இயற்கை கோபால்ட் மெழுகு',
    material_hi: 'क्वार्ट्ज पाउडर, मुल्तानी मिट्टी, प्राकृतिक कोबाल्ट ग्लेज',
    technique_en: 'Mould-pressed, hand-painted with cobalt oxide, low-temperature wood kiln fired',
    technique_ta: 'அச்சில் வார்த்து, கோபால்ட் தூரிகை ஓவியம் வரைந்து மிதமான சூளையிலிட்டு சுடப்பட்டது',
    technique_hi: 'सांचे में ढलाई, कोबाल्ट ऑक्साइड से हाथ से चित्रकारी और कम आंच पर पकाना',
    style_en: 'Indo-Persian Mughal Arabesque',
    style_ta: 'இந்தோ-பெர்சிய முகலாய கலை',
    style_hi: 'इंडो-पर्शियन मुग़ल शैली',
    colors: ['Cobalt Blue', 'Turquoise Cyan', 'Mustard Yellow', 'Opal White'],
    potential_uses_en: [
      'Luxury Heritage Hotel Centerpiece',
      'Art Gallery Collectible',
      'Premium Corporate Memento',
      'Architectural Foyer Accent',
    ],
    potential_uses_ta: [
      'பாரம்பரிய ஆடம்பர விடுதி அலங்காரம்',
      'கலைக்கூட சேகரிப்பு',
      'கார்ப்பரேட் நினைவுப்பரிசு',
      'வரவேற்பறை அலங்காரம்',
    ],
    potential_uses_hi: [
      'विलासिता हेरिटेज होटल केंद्र बिंदु',
      'आर्ट गैलरी संग्रहणीय वस्तु',
      'प्रीमियम कॉर्पोरेट स्मृति चिन्ह',
      'मुख्य लॉबी आंतरिक सज्जा',
    ],
    keywords: ['blue pottery', 'jaipur', 'ceramic', 'vase', 'hand painted', 'floral', 'rajasthan', 'gi tag'],
    description_en:
      'Authentic GI-registered Jaipur Blue Pottery vase meticulously hand-painted with vibrant Persian botanical motifs. Crafted using crushed quartz, glass frit, and natural mineral dyes without conventional potting clay.',
    description_ta:
      'பாரம்பரிய களிமண் இல்லாமல் குவார்ட்ஸ் படிகங்களால் உருவாக்கப்பட்ட உண்மையான ஜெய்ப்பூர் புளூ பாட்டரி குவளை. கோபால்ட் நீல வண்ணத்தில் வரையப்பட்ட மலர் கொடிகள் மற்றும் கண்ணாடி போன்ற பளபளப்பான பூச்சுடன் கூடியது.',
    description_hi:
      'प्रामाणिक जीआई-पंजीकृत जयपुर ब्लू पॉटरी फूलदान, जिस पर हाथ से सुंदर फारसी वनस्पति रूपांकनों को उकेरा गया है। क्वार्ट्ज और प्राकृतिक खनिजों से तैयार।',
    tags_en: ['Blue Pottery', 'Jaipur Craft', 'GI Tagged', 'Hand Painted', 'Ceramic Decor'],
    tags_ta: ['புளூ பாட்டரி', 'ஜெய்ப்பூர் கைவினை', 'புவிசார் குறியீடு', 'அலங்கார குவளை'],
    tags_hi: ['ब्लू पॉटरी', 'जयपुर शिल्प', 'जीआई टैग', 'सिरेमिक सजावट'],
    pricePerUnit: 2400,
    currency: 'INR',
    minimumOrderQuantity: 10,
    leadTimeDays: 21,
    stockAvailable: 35,
    isPublished: true,
    createdAt: '2026-08-28T09:00:00Z',
    confidenceScore: 98,
  },
  {
    id: 'prod-4',
    artisanId: 'artisan-1',
    artisanName: 'Master Artisan',
    artisanLocation: 'Madurai, Tamil Nadu',
    imageUrl: 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800&auto=format&fit=crop&q=80',
    title_en: 'Traditional Terracotta Wall Diya Hanging with Peacock Motif',
    title_ta: 'மயில் வடிவிலான பாரம்பரிய சுடுமண் சுவர் விளக்கு தொங்கல்',
    title_hi: 'पारंपरिक टेराकोटा मयूर आकृति दीवार दीया हैंगिंग',
    category_en: 'Home Decor & Pottery',
    category_ta: 'வீட்டு அலங்காரம் & மண்பாண்டங்கள்',
    category_hi: 'गृह सज्जा एवं मिट्टी के बर्तन',
    subcategory_en: 'Festive Oil Lamps & Wall Decor',
    subcategory_ta: 'பண்டிகை எண்ணெய் விளக்குகள் & சுவர் அலங்காரம்',
    subcategory_hi: 'त्योहारी तेल के दीये और दीवार सज्जा',
    material_en: 'Terracotta Clay, Natural Ochre Wash, Brass Ring',
    material_ta: 'சுடுமண் களிமண், இயற்கை செம்மண் பூச்சு, பித்தளை வளையம்',
    material_hi: 'टेराकोटा मिट्टी, प्राकृतिक गेरू लेप, पीतल का छल्ला',
    technique_en: 'Wheel-thrown base with hand-pinched plumage and engraved feathers',
    technique_ta: 'சக்கர சுழற்சி அடிவாரம் மற்றும் கைகளால் செதுக்கப்பட்ட மயில் இறகுகள்',
    technique_hi: 'चाक पर बना आधार एवं हाथ से नक्काशीदार पंखों की बनावट',
    style_en: 'South Indian Temple Folk',
    style_ta: 'தென்னிந்திய கோவில் நாட்டுப்புற கலை',
    style_hi: 'दक्षिण भारतीय मंदिर लोक कला',
    colors: ['Deep Terracotta', 'Burnt Umber', 'Raw Ochre'],
    potential_uses_en: [
      'Diwali & Festive Illumination',
      'Heritage Veranda Wall Accent',
      'Spiritual Room Lighting',
      'Artisan Souvenir',
    ],
    potential_uses_ta: [
      'தீபாவளி & பண்டிகை ஒளி அலங்காரம்',
      'பாரம்பரிய நடைபாதை சுவர் அலங்காரம்',
      'பூஜை அறை ஒளி',
      'கைவினை நினைவுப் பொருள்',
    ],
    potential_uses_hi: [
      'दीपावली एवं त्योहारी रोशनी',
      'विरासत बरामदा दीवार सज्जा',
      'पूजा कक्ष प्रकाश व्यवस्था',
      'शिल्प स्मृति चिन्ह',
    ],
    keywords: ['terracotta', 'diya', 'lamp', 'peacock', 'temple craft', 'clay lamp', 'festive', 'handcrafted'],
    description_en:
      'Handmade terracotta oil lamp designed for wall mounting, featuring a gracefully sculpted peacock spreading its crest. Crafted from purified river silt and low-fired for optimal oil absorption and thermal resistance.',
    description_ta:
      'சுவரில் பொருத்தும் வகையில் வடிவமைக்கப்பட்ட மயில் வடிவ சுடுமண் அகல் விளக்கு. ஆற்று வண்டல் மண்ணில் உருவாக்கப்பட்டு உறுதியாக சுடப்பட்டது.',
    description_hi:
      'दीवार पर लटकाने के लिए हाथ से तैयार टेराकोटा तेल का दीपक, जिस पर सुरुचिपूर्ण मोर की आकृति बनी है। शुद्ध मिट्टी से बना टिकाऊ शिल्प।',
    tags_en: ['Terracotta Diya', 'Peacock Lamp', 'Festive Decor', 'Temple Art', 'Handmade'],
    tags_ta: ['சுடுமண் விளக்கு', 'மயில் அகல் விளக்கு', 'பண்டிகை அலங்காரம்', 'கைவினை'],
    tags_hi: ['टेराकोटा दीया', 'मोर दीपक', 'त्योहारी सजावट', 'मंदिर शिल्प'],
    pricePerUnit: 850,
    currency: 'INR',
    minimumOrderQuantity: 25,
    leadTimeDays: 10,
    stockAvailable: 60,
    isPublished: true,
    createdAt: '2026-08-30T11:00:00Z',
    confidenceScore: 94,
  },
];

export const mockMarketOpportunities: MarketOpportunity[] = [
  {
    id: 'opp-1',
    title_en: 'Chennai National Handicrafts & Cultural Expo 2026',
    title_ta: 'சென்னை தேசிய கைவினை மற்றும் கலாச்சார பொருட்காட்சி 2026',
    title_hi: 'चेन्नई राष्ट्रीय हस्तशिल्प एवं सांस्कृतिक एक्सपो 2026',
    organizer: 'Tamil Nadu Handicrafts Development Corporation & Ministry of Textiles',
    location: 'Valluvar Kottam Grounds, Chennai, Tamil Nadu',
    type: 'Exhibition',
    categoryRequired: 'Handmade Jewellery',
    materialRequired: ['Terracotta Clay', 'Natural Dyes', 'Handmade Beads', 'Folk Fibers'],
    craftTechniquesAccepted: ['Hand-moulded', 'Kiln-fired', 'Miniature Painting', 'Traditional Metal Cast'],
    targetLocationScope: 'South India & Pan-India Artisans',
    expectedOrderVolume: '₹12,00,000 to ₹30,00,000 across 10 days',
    boothGrantSubsidized: true,
    deadline: '2026-10-15',
    eventDates: 'November 12 - 22, 2026',
    description_en:
      'Premier state-sponsored handicraft exposition connecting certified master artisans directly with retail connoisseurs, export procurement houses, and upscale design boutiques across India.',
    description_ta:
      'சான்றளிக்கப்பட்ட மாஸ்டர் கைவினைஞர்களை சில்லறை விற்பனையாளர்கள், ஏற்றுமதி நிறுவனங்கள் மற்றும் பிரத்யேக ஆடை அங்காடிகளுடன் நேரடியாக இணைக்கும் முன்னணி மாநில அரசு கைவினைப் பொருட்காட்சி.',
    description_hi:
      'प्रमाणित मास्टर शिल्पकारों को सीधे खुदरा खरीदारों, निर्यात एजेंसियों और प्रमुख डिज़ाइन बुटीक से जोड़ने वाली प्रमुख राज्य-प्रायोजित हस्तशिल्प प्रदर्शनी।',
    bannerImage: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=1000&auto=format&fit=crop&q=80',
  },
  {
    id: 'opp-2',
    title_en: 'Dastkar South Asian Craft Bazaar - Autumn Edition',
    title_ta: 'தஸ்த்கர் தெற்காசிய கைவினை சந்தை - இலையுதிர்கால பதிப்பு',
    title_hi: 'दस्तकार दक्षिण एशियाई शिल्प बाज़ार - शरद संस्करण',
    organizer: 'Dastkar Society for Crafts & Craftspeople',
    location: 'Nature Bazaar, Andheria Modh, New Delhi',
    type: 'Craft Fair',
    categoryRequired: 'Handmade Jewellery',
    materialRequired: ['Terracotta', 'Bamboo', 'Brass', 'Clay', 'Ceramic', 'Natural Fiber'],
    craftTechniquesAccepted: ['Hand-moulded', 'Hand-painted', 'Pottery Glaze', 'Traditional Weave'],
    targetLocationScope: 'National Master Artisans',
    expectedOrderVolume: '₹8,00,000 - ₹20,00,000',
    boothGrantSubsidized: true,
    deadline: '2026-09-30',
    eventDates: 'October 24 - November 04, 2026',
    description_en:
      'Renowned platform dedicated to traditional, tribal, and marginalized craft communities. Over 150,000 visitors, urban retail buyers, and design students gather for direct artisan sales.',
    description_ta:
      'பாரம்பரிய, பழங்குடி மற்றும் விளிம்புநிலை கைவினை சமூகங்களுக்கு அர்ப்பணிக்கப்பட்ட புகழ்பெற்ற தளம். நேரடி கைவினை விற்பனைக்காக 150,000 க்கும் மேற்பட்ட பார்வையாளர்கள் கூடுகிறார்கள்.',
    description_hi:
      'पारंपरिक, आदिवासी और हाशिए पर मौजूद शिल्प समुदायों को समर्पित प्रसिद्ध मंच। 1,50,000 से अधिक आगंतुक और शहरी खरीदार सीधे शिल्पकारों से खरीदारी करते हैं।',
    bannerImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=1000&auto=format&fit=crop&q=80',
  },
  {
    id: 'opp-3',
    title_en: 'EcoBoutique Pan-India Bulk Procurement for Sustainable Stores',
    title_ta: 'சுற்றுச்சூழல் நட்பு அங்காடிகளுக்கான அகில இந்திய மொத்த கொள்முதல்',
    title_hi: 'सस्टेनेबल स्टोर्स के लिए इकोबुटीक अखिल भारतीय थोक खरीद',
    organizer: 'GreenEarth Conscious Retail Consortium',
    location: 'Bengaluru / Mumbai (Direct Warehouse Delivery)',
    type: 'Wholesale Buyer',
    categoryRequired: 'Home Decor & Storage',
    materialRequired: ['Natural Bamboo', 'Wild Cane', 'Terracotta Clay', 'Natural Fibers'],
    craftTechniquesAccepted: ['Bamboo Weaving', 'Cane Splinting', 'Hand Pottery', 'Organic Polishing'],
    targetLocationScope: 'All India Verified Artisan Collectives',
    expectedOrderVolume: 'Recurring bulk PO: 500 to 2,000 units / month',
    boothGrantSubsidized: false,
    deadline: '2026-10-05',
    eventDates: 'Ongoing Contract Q4 2026',
    description_en:
      'Large sustainable retail chain seeking ongoing bulk supply of handmade bamboo baskets, terracotta accents, and organic tabletop decor for 45 retail stores across tier-1 cities.',
    description_ta:
      '45 சில்லறை விற்பனை கடைகளுக்காக கைவினை மூங்கில் கூடைகள் மற்றும் சுடுமண் அலங்காரங்களை தொடர்ந்து மொத்தமாக கொள்முதல் செய்ய விரும்பும் பெரிய சில்லறை விற்பனை சங்கிலி.',
    description_hi:
      'देश भर के 45 प्रमुख स्टोरों के लिए हस्तनिर्मित बांस की टोकरियों और जैविक घरेलू सजावट के नियमित थोक ऑर्डर की तलाश में प्रमुख सस्टेनेबल रिटेल चेन।',
    bannerImage: 'https://images.unsplash.com/photo-1590483736622-39da86788790?w=1000&auto=format&fit=crop&q=80',
  },
  {
    id: 'opp-4',
    title_en: 'Royal Heritage Hotels Diwali Corporate Gifting Procurement',
    title_ta: 'ராயல் ஹெரிடேஜ் ஹோட்டல்ஸ் தீபாவளி கார்ப்பரேட் பரிசு கொள்முதல்',
    title_hi: 'रॉयल हेरिटेज होटल्स दीपावली कॉर्पोरेट उपहार खरीद',
    organizer: 'Virasat Hospitality Procurement Division',
    location: 'Jaipur, Rajasthan & New Delhi HQ',
    type: 'Corporate Gifting',
    categoryRequired: 'Home Decor & Pottery',
    materialRequired: ['Quartz Powder', 'Cobalt Glaze', 'Terracotta Clay', 'Brass'],
    craftTechniquesAccepted: ['Blue Pottery', 'Hand Carving', 'Glazed Ceramic', 'Terracotta Moulding'],
    targetLocationScope: 'GI Tag Craft Clusters (Jaipur, Madurai, Khurja)',
    expectedOrderVolume: '₹15,00,000 (1,200 curated gift hampers)',
    boothGrantSubsidized: false,
    deadline: '2026-09-28',
    eventDates: 'Delivery by October 20, 2026',
    description_en:
      'High-profile luxury hospitality chain procuring authentic GI-tagged Blue Pottery vases and traditional handcrafted terracotta festive diyas for executive patron gifting.',
    description_ta:
      'உயர்ரக சொகுசு விருந்தோம்பல் சங்கிலி தனது விஐபி வாடிக்கையாளர்களுக்கான பரிசுப் பெட்டிகளுக்காக புவிசார் குறியீடு பெற்ற நீல மண்பாண்டங்கள் மற்றும் பாரம்பரிய சுடுமண் விளக்குகளை கொள்முதல் செய்கிறது.',
    description_hi:
      'प्रमुख लक्जरी होटल श्रृंखला अपने वीआईपी संरक्षकों के त्योहारी उपहारों के लिए प्रामाणिक जीआई-टैग ब्लू पॉटरी फूलदान और टेराकोटा दीपकों की खरीद कर रही है।',
    bannerImage: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=1000&auto=format&fit=crop&q=80',
  },
  {
    id: 'opp-5',
    title_en: 'Kala Heritage Urban Design Boutique Annual Showcase',
    title_ta: 'கலா ஹெரிடேஜ் நகர்ப்புற வடிவமைப்பு பொட்டிக் வருடாந்திர கண்காட்சி',
    title_hi: 'कला हेरिटेज अर्बन डिज़ाइन बुटीक वार्षिक शोकेस',
    organizer: 'Kala Design Studio & Guild',
    location: 'Kala Ghoda Art Precinct, Mumbai',
    type: 'Boutique Store',
    categoryRequired: 'Handmade Jewellery',
    materialRequired: ['Terracotta', 'Handwoven Silk', 'Silver', 'Natural Pigments'],
    craftTechniquesAccepted: ['Hand-moulded', 'Filigree', 'Pit-loom Weave', 'Folk Painting'],
    targetLocationScope: 'Heritage Craft Custodians',
    expectedOrderVolume: '₹6,00,000 - ₹12,00,000',
    boothGrantSubsidized: false,
    deadline: '2026-10-20',
    eventDates: 'December 05 - 15, 2026',
    description_en:
      'Curated concept boutique in Mumbai featuring limited-edition master craft items with direct artisan storytelling cards and fair-trade revenue sharing.',
    description_ta:
      'மும்பையில் உள்ள பிரத்யேக வடிவமைப்பு அங்காடி, கைவினைஞர்களின் நேரடி கதைகளுடன் கூடிய பிரத்யேக கலைப்படைப்புகளை காட்சிப்படுத்துகிறது.',
    description_hi:
      'मुंबई का प्रतिष्ठित कॉन्सेप्ट बुटीक जो शिल्पकारों की प्रामाणिक कहानियों के साथ विशेष हस्तनिर्मित कलाकृतियों को प्रदर्शित करता है।',
    bannerImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1000&auto=format&fit=crop&q=80',
  },
];

export const initialEnquiries: Enquiry[] = [
  {
    id: 'enq-1',
    artisanId: 'artisan-1',
    artisanName: 'Master Artisan',
    buyerId: 'buyer-1',
    buyerName: 'Procurement Partner',
    buyerOrg: 'Sustainable Retail Store',
    productId: 'prod-1',
    productTitle: 'Handcrafted Kathakali Face Terracotta Necklace Set',
    productImage: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80',
    targetQuantity: 40,
    offeredPricePerUnit: 1350,
    initialMessage:
      'Namaste, we love the intricate Kathakali facial detailing. We want to place an order of 40 units for our festive collection. Can you deliver by early October?',
    status: 'Negotiating',
    opportunityId: 'opp-1',
    opportunityTitle: 'Chennai National Handicrafts Expo',
    createdAt: '2026-08-31T09:30:00Z',
    updatedAt: '2026-09-02T15:45:00Z',
    messages: [
      {
        id: 'msg-1',
        senderId: 'user-buyer-1',
        senderName: 'Procurement Partner',
        senderRole: 'buyer',
        content:
          'Namaste, we love the intricate Kathakali facial detailing. We want to place an order of 40 units for our festive collection. Can you deliver by early October?',
        timestamp: '2026-08-31T09:30:00Z',
      },
      {
        id: 'msg-2',
        senderId: 'user-artisan-1',
        senderName: 'Master Artisan',
        senderRole: 'artisan',
        content:
          'Vanakkam. Thank you for your appreciation! Yes, 40 sets can be crafted and kiln-fired within 14 days. We pack each piece in recycled handmade palm-leaf boxes. If you can accept ₹1,380 per unit for the complete set with earrings, we can start preparation immediately.',
        timestamp: '2026-09-01T11:20:00Z',
      },
      {
        id: 'msg-3',
        senderId: 'user-buyer-1',
        senderName: 'Procurement Partner',
        senderRole: 'buyer',
        content:
          '₹1,380 is acceptable with palm-leaf protective packaging included! Could you share a quick photo of the matching terracotta earrings once the first batch is out of the kiln?',
        timestamp: '2026-09-02T15:45:00Z',
      },
    ],
  },
  {
    id: 'enq-2',
    artisanId: 'artisan-1',
    artisanName: 'Master Artisan',
    buyerId: 'buyer-2',
    buyerName: 'Procurement Lead',
    buyerOrg: 'Heritage Hospitality Group',
    productId: 'prod-4',
    productTitle: 'Traditional Terracotta Wall Diya Hanging with Peacock Motif',
    productImage: 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=800&auto=format&fit=crop&q=80',
    targetQuantity: 100,
    offeredPricePerUnit: 800,
    initialMessage:
      'Respected Artisan, we wish to order 100 pieces of your peacock wall diyas for our heritage properties for festive decor. Please let us know your production schedule.',
    status: 'Responded',
    opportunityId: 'opp-4',
    opportunityTitle: 'Royal Heritage Hotels Diwali Corporate Gifting Procurement',
    createdAt: '2026-09-03T14:10:00Z',
    updatedAt: '2026-09-04T10:00:00Z',
    messages: [
      {
        id: 'msg-201',
        senderId: 'user-buyer-2',
        senderName: 'Procurement Lead',
        senderRole: 'buyer',
        content:
          'Respected Artisan, we wish to order 100 pieces of your peacock wall diyas for our heritage properties for festive decor. Please let us know your production schedule.',
        timestamp: '2026-09-03T14:10:00Z',
      },
      {
        id: 'msg-202',
        senderId: 'user-artisan-1',
        senderName: 'Master Artisan',
        senderRole: 'artisan',
        content:
          'Namaste! For 100 peacock diyas, our village guild will allocate 3 master potters. We can deliver in two batches of 50 units each by October 12th.',
        timestamp: '2026-09-04T10:00:00Z',
      },
    ],
  },
];
